### ISSUE TITLE
Errors on Startup | SQLAlchemyDebugPanel

### ISSUE THREAD

**Issue by SaymV** [semirook/flask-kit#2]
![screenshot from 2013-06-25 14 26 25](https://f.cloud.github.com/assets/1234808/705828/f443ed58-dddd-11e2-95e6-e895bcb4802f.png)
I'm not sure if the decoding of the request header is related, I'm assuming it isn't. I was in a virtualenv, this occurred as I navigated to localhost:5000.

**Comment by semirook** [comment]
Fixed in 9af3408, just works.
