### ISSUE TITLE
Integrating Restless

### ISSUE THREAD

**Issue by RockyRoad29** [semirook/flask-kit#5]
Hello,

Thanks Roman for this great "backbone". I've been working on extending it for a couple of weeks now (https://github.com/RockyRoad29/flask-kit), including [documentation](http://rockyroad29.github.io/flask-kit/api/index.html).

Now trying to use Flask-Restless I have a new AppFactory problem.
This extension implements [init_app](http://flask-restless.readthedocs.org/en/latest/api.html#flask.ext.restless.APIManager.init_app), but it takes extra arguments like 'db' or 'session'.

Should I, as you did for gravatar and toolbar, declare it as lambda at the end of `ext.py` ?
```python
gravatar = lambda app: Gravatar(app, size=50)  # has no init_app()
toolbar = lambda app: DebugToolbarExtension(app)  # has no init_app()

from flask.ext.restless import APIManager
api_manager = lambda app: APIManager(app, flask_sqlalchemy_db=db) # needs db as init_app argument
```
But I realize I don't understand how it is supposed to work. Can you help me about that ?

Another option might be to extend `AppFactory._bind_extensions()` to accept extra parameters but I think it might get tricky. Any idea ?

**Comment by semirook** [comment]
Thanks for your feedback and your solution is almost correct. Fixed in 9af3408
